package com.dev.aiassistant.ai.gemini;

import com.dev.aiassistant.ai.AiProvider;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestClient;
import org.springframework.web.client.RestClientResponseException;

import java.util.List;
import java.util.Map;

@Component
public class GeminiAiProvider implements AiProvider {
    private final RestClient restClient; private final String configuredApiKey; private final String preferredModel; private volatile String runtimeApiKey; private volatile String runtimeModel;
    public GeminiAiProvider(RestClient.Builder builder,@Value("${app.ai.gemini.api-key:}") String apiKey,@Value("${app.ai.gemini.model:}") String model,@Value("${app.ai.gemini.base-url:https://generativelanguage.googleapis.com}") String baseUrl){this.restClient=builder.baseUrl(baseUrl).build();this.configuredApiKey=apiKey;this.preferredModel=model;}
    @Override public String id(){return "gemini";}
    public void useRuntimeApiKey(String value){runtimeApiKey=value;runtimeModel=null;}
    public boolean configured(){return !apiKey().isBlank();}
    public String validateConnection(){String key=apiKey();if(key.isBlank())throw new IllegalStateException("Ingresa una API key de Gemini.");try{ModelList response=restClient.get().uri(b->b.path("/v1beta/models").queryParam("key",key).queryParam("pageSize",1000).build()).retrieve().body(ModelList.class);String selected=selectModel(response);runtimeModel=selected;return selected;}catch(RestClientResponseException ex){int status=ex.getStatusCode().value();if(status==400||status==401||status==403)throw new IllegalStateException("Gemini no aceptó la API key o el proyecto no tiene acceso a Gemini (HTTP "+status+").",ex);if(status==429)throw new IllegalStateException("Gemini alcanzó el límite temporal/cuota de la API (HTTP 429).",ex);throw new IllegalStateException("No fue posible validar Gemini (HTTP "+status+").",ex);}catch(RuntimeException ex){if(ex instanceof IllegalStateException state)throw state;throw new IllegalStateException("No fue posible comunicarse con Gemini para consultar los modelos disponibles.",ex);}}
    @Override public String generate(String prompt){String key=apiKey();if(key.isBlank())throw new IllegalStateException("Gemini no está configurado. Ingresa y valida una API key en Configuración.");String selected=runtimeModel;if(selected==null||selected.isBlank())selected=validateConnection();Map<String,Object> request=Map.of("contents",List.of(Map.of("parts",List.of(Map.of("text",prompt)))));try{GeminiResponse response=restClient.post().uri(b->b.path("/v1beta/models/{model}:generateContent").queryParam("key",key).build(selected)).contentType(MediaType.APPLICATION_JSON).body(request).retrieve().body(GeminiResponse.class);return extractText(response);}catch(RestClientResponseException ex){int status=ex.getStatusCode().value();if(status==429)throw new IllegalStateException("Gemini alcanzó el límite temporal/cuota de la API (HTTP 429).",ex);if(status==404)throw new IllegalStateException("El modelo de Gemini seleccionado ya no está disponible para generateContent. Vuelve a probar la conexión para actualizarlo.",ex);throw new IllegalStateException("Gemini rechazó la generación (HTTP "+status+").",ex);}catch(RuntimeException ex){if(ex instanceof IllegalStateException state)throw state;throw new IllegalStateException("No fue posible comunicarse con Gemini.",ex);}}
    private String selectModel(ModelList response){if(response==null||response.models()==null)throw new IllegalStateException("Gemini respondió sin modelos disponibles para esta API key.");List<ModelInfo> compatible=response.models().stream().filter(m->m.name()!=null&&m.supportedGenerationMethods()!=null&&m.supportedGenerationMethods().contains("generateContent")).toList();if(compatible.isEmpty())throw new IllegalStateException("La API key es válida, pero no tiene modelos disponibles que soporten generateContent.");if(preferredModel!=null&&!preferredModel.isBlank()){String wanted=normalize(preferredModel);for(ModelInfo m:compatible)if(normalize(m.name()).equals(wanted))return normalize(m.name());}for(String candidate:List.of("gemini-3.5-flash-lite","gemini-3.1-flash-lite","gemini-3.5-flash","gemini-3-flash","gemini-2.5-flash-lite","gemini-2.5-flash"))for(ModelInfo m:compatible)if(normalize(m.name()).equals(candidate))return candidate;return normalize(compatible.getFirst().name());}
    private String normalize(String value){return value.startsWith("models/")?value.substring("models/".length()):value;}
    private String apiKey(){String value=runtimeApiKey;return value!=null&&!value.isBlank()?value:(configuredApiKey==null?"":configuredApiKey);}
    private String extractText(GeminiResponse response){if(response==null||response.candidates()==null||response.candidates().isEmpty())throw new IllegalStateException("Gemini respondió sin contenido generado.");Candidate candidate=response.candidates().getFirst();if(candidate.content()==null||candidate.content().parts()==null||candidate.content().parts().isEmpty())throw new IllegalStateException("Gemini respondió sin texto generado.");String text=candidate.content().parts().stream().map(Part::text).filter(v->v!=null&&!v.isBlank()).reduce("",(a,b)->a+b);if(text.isBlank())throw new IllegalStateException("Gemini respondió sin texto generado.");return text;}
    public record ModelList(List<ModelInfo> models){} public record ModelInfo(String name,List<String> supportedGenerationMethods){} public record GeminiResponse(List<Candidate> candidates){} public record Candidate(Content content){} public record Content(List<Part> parts){} public record Part(String text){}
}
